[package]
name = "_scippneutron_algorithms_lib"
version = "0.0.0"  # The version is set in pyproject.toml
edition.workspace = true
rust-version.workspace = true

[lib]
name = "_scippneutron_algorithms_lib"
crate-type = ["cdylib"]

[dependencies]
algo_impl = { path = "../algo_impl" }

ndarray = { workspace = true }
numpy = { workspace = true }
pyo3 = { workspace = true }
