[package]
name = "_scippneutron_algorithms_lib"
version = "26.7.0"
edition = "2024"

[lib]
name = "_scippneutron_algorithms_lib"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.17.2"
numpy = "0.29"
pyo3 = { version = "0.29", features = ["abi3", "abi3-py311"] }

[profile.release]
codegen-units = 1
lto = "fat"
strip = true
